import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import Footer from '@/components/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TTVP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode  
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body >
        <header className='bg-white'><Navbar/></header>
        {children}
        <footer><Footer/></footer>
      </body>
    </html>
  )
}
